version: '3'
services:
  back:
    build:
      context: './Back'
      dockerfile: './Back/Dockerfile'
    restart: unless-stopped
    links:
      - db
    environment:
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "8000:8000"
    volumes:
      - "./Back:/usr/src/app/api"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: DB_HOSTNAME
    restart: unless-stopped
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "3002:80"