version: "3.7"

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  server:
    build: ./Back
    expose:
      - 8000
    environment:
      <<: *common-variables
    ports:
      - 8000:8000
    volumes:
      - ./Back:/app
    command: npm start
    tty: true

  client:
    build: ./Front
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./Front/src:/app/src
    links:
      - server
    command: npm start
    tty: true